//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaClientes
    {
        public string Cod_cli { get; set; }
        public string Raz_soc_cli { get; set; }
        public string Ruc_cli { get; set; }
        public string Dir_cli { get; set; }
        public string Tel_cli { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Est_cli { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public Nullable<int> Antiguedad { get; set; }
        public string Estado { get; set; }
        public string Tipo { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string Usu_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public Nullable<decimal> Deuda { get; set; }
    }
}
