//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaFacturas
    {
        public string Num_fac { get; set; }
        public System.DateTime Fec_fac { get; set; }
        public Nullable<System.DateTime> Fec_can { get; set; }
        public string Cod_cli { get; set; }
        public string Raz_soc_cli { get; set; }
        public string Ruc_cli { get; set; }
        public string Tel_cli { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public Nullable<double> Total { get; set; }
        public string Est_fac { get; set; }
        public string Estado { get; set; }
        public string Cod_ven { get; set; }
        public string Nom_ven { get; set; }
        public string Ape_ven { get; set; }
    }
}
