//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindows.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Ventas")]
    [System.SerializableAttribute()]
    public partial class ClienteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CantFacturasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DeudaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dir_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Raz_soc_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ruc_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CantFacturas {
            get {
                return this.CantFacturasField;
            }
            set {
                if ((this.CantFacturasField.Equals(value) != true)) {
                    this.CantFacturasField = value;
                    this.RaisePropertyChanged("CantFacturas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_cli {
            get {
                return this.Cod_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_cliField, value) != true)) {
                    this.Cod_cliField = value;
                    this.RaisePropertyChanged("Cod_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Deuda {
            get {
                return this.DeudaField;
            }
            set {
                if ((this.DeudaField.Equals(value) != true)) {
                    this.DeudaField = value;
                    this.RaisePropertyChanged("Deuda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_cli {
            get {
                return this.Dir_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Dir_cliField, value) != true)) {
                    this.Dir_cliField = value;
                    this.RaisePropertyChanged("Dir_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli {
            get {
                return this.Raz_soc_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Raz_soc_cliField, value) != true)) {
                    this.Raz_soc_cliField = value;
                    this.RaisePropertyChanged("Raz_soc_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_cli {
            get {
                return this.Ruc_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruc_cliField, value) != true)) {
                    this.Ruc_cliField = value;
                    this.RaisePropertyChanged("Ruc_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_cli {
            get {
                return this.Tel_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_cliField, value) != true)) {
                    this.Tel_cliField = value;
                    this.RaisePropertyChanged("Tel_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        TestWindows.ProxyCliente.ClienteBE ConsultarCliente(string strCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<TestWindows.ProxyCliente.ClienteBE> ConsultarClienteAsync(string strCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/CalcularDeudaCliente", ReplyAction="http://tempuri.org/IServicioCliente/CalcularDeudaClienteResponse")]
        float CalcularDeudaCliente(string strCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/CalcularDeudaCliente", ReplyAction="http://tempuri.org/IServicioCliente/CalcularDeudaClienteResponse")]
        System.Threading.Tasks.Task<float> CalcularDeudaClienteAsync(string strCod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : TestWindows.ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<TestWindows.ProxyCliente.IServicioCliente>, TestWindows.ProxyCliente.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWindows.ProxyCliente.ClienteBE ConsultarCliente(string strCod) {
            return base.Channel.ConsultarCliente(strCod);
        }
        
        public System.Threading.Tasks.Task<TestWindows.ProxyCliente.ClienteBE> ConsultarClienteAsync(string strCod) {
            return base.Channel.ConsultarClienteAsync(strCod);
        }
        
        public float CalcularDeudaCliente(string strCod) {
            return base.Channel.CalcularDeudaCliente(strCod);
        }
        
        public System.Threading.Tasks.Task<float> CalcularDeudaClienteAsync(string strCod) {
            return base.Channel.CalcularDeudaClienteAsync(strCod);
        }
    }
}
