//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindows.ProxyFactura {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Ventas")]
    [System.SerializableAttribute()]
    public partial class FacturaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Est_facField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_canField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_facField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_facField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Raz_soc_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ruc_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_ven {
            get {
                return this.Ape_venField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_venField, value) != true)) {
                    this.Ape_venField = value;
                    this.RaisePropertyChanged("Ape_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_cli {
            get {
                return this.Cod_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_cliField, value) != true)) {
                    this.Cod_cliField = value;
                    this.RaisePropertyChanged("Cod_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_ven {
            get {
                return this.Cod_venField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_venField, value) != true)) {
                    this.Cod_venField = value;
                    this.RaisePropertyChanged("Cod_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Est_fac {
            get {
                return this.Est_facField;
            }
            set {
                if ((object.ReferenceEquals(this.Est_facField, value) != true)) {
                    this.Est_facField = value;
                    this.RaisePropertyChanged("Est_fac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_can {
            get {
                return this.Fec_canField;
            }
            set {
                if ((this.Fec_canField.Equals(value) != true)) {
                    this.Fec_canField = value;
                    this.RaisePropertyChanged("Fec_can");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_fac {
            get {
                return this.Fec_facField;
            }
            set {
                if ((this.Fec_facField.Equals(value) != true)) {
                    this.Fec_facField = value;
                    this.RaisePropertyChanged("Fec_fac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_ven {
            get {
                return this.Nom_venField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_venField, value) != true)) {
                    this.Nom_venField = value;
                    this.RaisePropertyChanged("Nom_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_fac {
            get {
                return this.Num_facField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_facField, value) != true)) {
                    this.Num_facField = value;
                    this.RaisePropertyChanged("Num_fac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli {
            get {
                return this.Raz_soc_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Raz_soc_cliField, value) != true)) {
                    this.Raz_soc_cliField = value;
                    this.RaisePropertyChanged("Raz_soc_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_cli {
            get {
                return this.Ruc_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Ruc_cliField, value) != true)) {
                    this.Ruc_cliField = value;
                    this.RaisePropertyChanged("Ruc_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_cli {
            get {
                return this.Tel_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_cliField, value) != true)) {
                    this.Tel_cliField = value;
                    this.RaisePropertyChanged("Tel_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyFactura.IServicioFactura")]
    public interface IServicioFactura {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/GetAllFacturasClienteFechas", ReplyAction="http://tempuri.org/IServicioFactura/GetAllFacturasClienteFechasResponse")]
        TestWindows.ProxyFactura.FacturaBE[] GetAllFacturasClienteFechas(string strCod, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/GetAllFacturasClienteFechas", ReplyAction="http://tempuri.org/IServicioFactura/GetAllFacturasClienteFechasResponse")]
        System.Threading.Tasks.Task<TestWindows.ProxyFactura.FacturaBE[]> GetAllFacturasClienteFechasAsync(string strCod, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/GetAllFacturasVendedorFechas", ReplyAction="http://tempuri.org/IServicioFactura/GetAllFacturasVendedorFechasResponse")]
        TestWindows.ProxyFactura.FacturaBE[] GetAllFacturasVendedorFechas(string strCod, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/GetAllFacturasVendedorFechas", ReplyAction="http://tempuri.org/IServicioFactura/GetAllFacturasVendedorFechasResponse")]
        System.Threading.Tasks.Task<TestWindows.ProxyFactura.FacturaBE[]> GetAllFacturasVendedorFechasAsync(string strCod, System.DateTime fecini, System.DateTime fecfin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioFacturaChannel : TestWindows.ProxyFactura.IServicioFactura, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFacturaClient : System.ServiceModel.ClientBase<TestWindows.ProxyFactura.IServicioFactura>, TestWindows.ProxyFactura.IServicioFactura {
        
        public ServicioFacturaClient() {
        }
        
        public ServicioFacturaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFacturaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWindows.ProxyFactura.FacturaBE[] GetAllFacturasClienteFechas(string strCod, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllFacturasClienteFechas(strCod, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<TestWindows.ProxyFactura.FacturaBE[]> GetAllFacturasClienteFechasAsync(string strCod, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllFacturasClienteFechasAsync(strCod, fecini, fecfin);
        }
        
        public TestWindows.ProxyFactura.FacturaBE[] GetAllFacturasVendedorFechas(string strCod, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllFacturasVendedorFechas(strCod, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<TestWindows.ProxyFactura.FacturaBE[]> GetAllFacturasVendedorFechasAsync(string strCod, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.GetAllFacturasVendedorFechasAsync(strCod, fecini, fecfin);
        }
    }
}
